name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # 获取 Lagrange.Core 子模块的提交哈希，并作为后续缓存 key 的一部分
    - name: Get Lagrange.Core commit hash
      id: lagrange_core_commit
      run: echo "commit=$(git -C Lagrange.Core rev-parse HEAD)" >> $GITHUB_OUTPUT

    # 恢复 Lagrange-Core 构建结果的缓存
    - name: Restore Lagrange-Core build cache
      uses: actions/cache@v4
      with:
        path: Lagrange.Core/Lagrange.Core/bin
        key: ${{ runner.os }}-Lagrange-Core-${{ steps.lagrange_core_commit.outputs.commit }}

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish the application
      run: dotnet publish -c Debug QQAvatarUploader -r win-x64

    # Upload the application: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win-x64.exe
        path: QQAvatarUploader/bin/Debug/net9.0/win-x64/publish/QQAvatarUploader.exe
        
